import { Product } from "@/types/home/home";

export const mockProducts: Array<Product> = [
  {
    id: 1,
    availabilityStatus: "In Stock",
    brand: "Brand A",
    category: "Electronics",
    description: "A high-quality electronic product.",
    dimensions: {
      width: 10,
      height: 15,
      depth: 5,
    },
    discountPercentage: 10,
    images: [
      "https://example.com/product1-image1.jpg",
      "https://example.com/product1-image2.jpg",
    ],
    meta: {
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2023-06-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 100,
    rating: 4.5,
    returnPolicy: "30-day return policy",
    reviews: [
      {
        revierEmail: "reviewer1@example.com",
        revierName: "Reviewer One",
        rating: 5,
        comment: "Great product, highly recommend!",
        date: "2023-03-01T00:00:00Z",
      },
    ],
    shippingInformation: "Free shipping on orders over $50",
    sku: "SKU12345",
    stock: 50,
    tags: ["electronics", "gadgets", "new"],
    thumbnail: "https://example.com/product1-thumbnail.jpg",
    title: "Product A",
    warrantyInformation: "2-year limited warranty",
    weight: 1.2,
  },
  {
    id: 2,
    availabilityStatus: "Limited Stock",
    brand: "Brand B",
    category: "Home Appliances",
    description: "An essential home appliance for your kitchen.",
    dimensions: {
      width: 20,
      height: 30,
      depth: 15,
    },
    discountPercentage: 15,
    images: [
      "https://example.com/product2-image1.jpg",
      "https://example.com/product2-image2.jpg",
    ],
    meta: {
      createdAt: "2023-02-01T00:00:00Z",
      updatedAt: "2023-07-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 250,
    rating: 4.0,
    returnPolicy: "60-day return policy",
    reviews: [
      {
        revierEmail: "reviewer2@example.com",
        revierName: "Reviewer Two",
        rating: 4,
        comment: "Good quality, but could be better.",
        date: "2023-05-01T00:00:00Z",
      },
    ],
    shippingInformation: "Standard shipping applies",
    sku: "SKU67890",
    stock: 20,
    tags: ["home", "appliances", "kitchen"],
    thumbnail: "https://example.com/product2-thumbnail.jpg",
    title: "Product B",
    warrantyInformation: "1-year manufacturer warranty",
    weight: 2.5,
  },
  {
    id: 3,
    availabilityStatus: "Out of Stock",
    brand: "Brand C",
    category: "Furniture",
    description: "A stylish piece of furniture for your living room.",
    dimensions: {
      width: 50,
      height: 60,
      depth: 40,
    },
    discountPercentage: 20,
    images: [
      "https://example.com/product3-image1.jpg",
      "https://example.com/product3-image2.jpg",
    ],
    meta: {
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2023-08-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 500,
    rating: 4.8,
    returnPolicy: "No returns allowed",
    reviews: [
      {
        revierEmail: "reviewer3@example.com",
        revierName: "Reviewer Three",
        rating: 5,
        comment: "Absolutely love this piece!",
        date: "2023-06-01T00:00:00Z",
      },
    ],
    shippingInformation: "Heavy item, additional shipping fees apply",
    sku: "SKU54321",
    stock: 0,
    tags: ["furniture", "living room", "luxury"],
    thumbnail: "https://example.com/product3-thumbnail.jpg",
    title: "Product C",
    warrantyInformation: "5-year extended warranty",
    weight: 30,
  },
];

export const expectedFilteredProducts: Array<Product> = [
  {
    availabilityStatus: "In Stock",
    brand: "Brand A",
    category: "Electronics",
    description: "A high-quality electronic product.",
    dimensions: {
      depth: 5,
      height: 15,
      width: 10,
    },
    discountPercentage: 10,
    id: 1,
    images: [
      "https://example.com/product1-image1.jpg",
      "https://example.com/product1-image2.jpg",
    ],
    meta: {
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2023-06-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 100,
    rating: 4.5,
    returnPolicy: "30-day return policy",
    reviews: [
      {
        comment: "Great product, highly recommend!",
        date: "2023-03-01T00:00:00Z",
        rating: 5,
        revierEmail: "reviewer1@example.com",
        revierName: "Reviewer One",
      },
    ],
    shippingInformation: "Free shipping on orders over $50",
    sku: "SKU12345",
    stock: 50,
    tags: ["electronics", "gadgets", "new"],
    thumbnail: "https://example.com/product1-thumbnail.jpg",
    title: "Product A",
    warrantyInformation: "2-year limited warranty",
    weight: 1.2,
  },
];

export const expectedProductsInDescendingOrder: Array<Product> = [
  {
    availabilityStatus: "Out of Stock",
    brand: "Brand C",
    category: "Furniture",
    description: "A stylish piece of furniture for your living room.",
    dimensions: {
      depth: 40,
      height: 60,
      width: 50,
    },
    discountPercentage: 20,
    id: 3,
    images: [
      "https://example.com/product3-image1.jpg",
      "https://example.com/product3-image2.jpg",
    ],
    meta: {
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2023-08-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 500,
    rating: 4.8,
    returnPolicy: "No returns allowed",
    reviews: [
      {
        comment: "Absolutely love this piece!",
        date: "2023-06-01T00:00:00Z",
        rating: 5,
        revierEmail: "reviewer3@example.com",
        revierName: "Reviewer Three",
      },
    ],
    shippingInformation: "Heavy item, additional shipping fees apply",
    sku: "SKU54321",
    stock: 0,
    tags: ["furniture", "living room", "luxury"],
    thumbnail: "https://example.com/product3-thumbnail.jpg",
    title: "Product C",
    warrantyInformation: "5-year extended warranty",
    weight: 30,
  },
  {
    availabilityStatus: "Limited Stock",
    brand: "Brand B",
    category: "Home Appliances",
    description: "An essential home appliance for your kitchen.",
    dimensions: {
      depth: 15,
      height: 30,
      width: 20,
    },
    discountPercentage: 15,
    id: 2,
    images: [
      "https://example.com/product2-image1.jpg",
      "https://example.com/product2-image2.jpg",
    ],
    meta: {
      createdAt: "2023-02-01T00:00:00Z",
      updatedAt: "2023-07-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 250,
    rating: 4,
    returnPolicy: "60-day return policy",
    reviews: [
      {
        comment: "Good quality, but could be better.",
        date: "2023-05-01T00:00:00Z",
        rating: 4,
        revierEmail: "reviewer2@example.com",
        revierName: "Reviewer Two",
      },
    ],
    shippingInformation: "Standard shipping applies",
    sku: "SKU67890",
    stock: 20,
    tags: ["home", "appliances", "kitchen"],
    thumbnail: "https://example.com/product2-thumbnail.jpg",
    title: "Product B",
    warrantyInformation: "1-year manufacturer warranty",
    weight: 2.5,
  },
  {
    availabilityStatus: "In Stock",
    brand: "Brand A",
    category: "Electronics",
    description: "A high-quality electronic product.",
    dimensions: {
      depth: 5,
      height: 15,
      width: 10,
    },
    discountPercentage: 10,
    id: 1,
    images: [
      "https://example.com/product1-image1.jpg",
      "https://example.com/product1-image2.jpg",
    ],
    meta: {
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2023-06-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 100,
    rating: 4.5,
    returnPolicy: "30-day return policy",
    reviews: [
      {
        comment: "Great product, highly recommend!",
        date: "2023-03-01T00:00:00Z",
        rating: 5,
        revierEmail: "reviewer1@example.com",
        revierName: "Reviewer One",
      },
    ],
    shippingInformation: "Free shipping on orders over $50",
    sku: "SKU12345",
    stock: 50,
    tags: ["electronics", "gadgets", "new"],
    thumbnail: "https://example.com/product1-thumbnail.jpg",
    title: "Product A",
    warrantyInformation: "2-year limited warranty",
    weight: 1.2,
  },
];

export const expectedProductsInAscendingOrder = [
  {
    availabilityStatus: "In Stock",
    brand: "Brand A",
    category: "Electronics",
    description: "A high-quality electronic product.",
    dimensions: {
      depth: 5,
      height: 15,
      width: 10,
    },
    discountPercentage: 10,
    id: 1,
    images: [
      "https://example.com/product1-image1.jpg",
      "https://example.com/product1-image2.jpg",
    ],
    meta: {
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2023-06-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 100,
    rating: 4.5,
    returnPolicy: "30-day return policy",
    reviews: [
      {
        comment: "Great product, highly recommend!",
        date: "2023-03-01T00:00:00Z",
        rating: 5,
        revierEmail: "reviewer1@example.com",
        revierName: "Reviewer One",
      },
    ],
    shippingInformation: "Free shipping on orders over $50",
    sku: "SKU12345",
    stock: 50,
    tags: ["electronics", "gadgets", "new"],
    thumbnail: "https://example.com/product1-thumbnail.jpg",
    title: "Product A",
    warrantyInformation: "2-year limited warranty",
    weight: 1.2,
  },
  {
    availabilityStatus: "Limited Stock",
    brand: "Brand B",
    category: "Home Appliances",
    description: "An essential home appliance for your kitchen.",
    dimensions: {
      depth: 15,
      height: 30,
      width: 20,
    },
    discountPercentage: 15,
    id: 2,
    images: [
      "https://example.com/product2-image1.jpg",
      "https://example.com/product2-image2.jpg",
    ],
    meta: {
      createdAt: "2023-02-01T00:00:00Z",
      updatedAt: "2023-07-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 250,
    rating: 4,
    returnPolicy: "60-day return policy",
    reviews: [
      {
        comment: "Good quality, but could be better.",
        date: "2023-05-01T00:00:00Z",
        rating: 4,
        revierEmail: "reviewer2@example.com",
        revierName: "Reviewer Two",
      },
    ],
    shippingInformation: "Standard shipping applies",
    sku: "SKU67890",
    stock: 20,
    tags: ["home", "appliances", "kitchen"],
    thumbnail: "https://example.com/product2-thumbnail.jpg",
    title: "Product B",
    warrantyInformation: "1-year manufacturer warranty",
    weight: 2.5,
  },
  {
    availabilityStatus: "Out of Stock",
    brand: "Brand C",
    category: "Furniture",
    description: "A stylish piece of furniture for your living room.",
    dimensions: {
      depth: 40,
      height: 60,
      width: 50,
    },
    discountPercentage: 20,
    id: 3,
    images: [
      "https://example.com/product3-image1.jpg",
      "https://example.com/product3-image2.jpg",
    ],
    meta: {
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2023-08-01T00:00:00Z",
    },
    minimumOrderQuantity: 1,
    price: 500,
    rating: 4.8,
    returnPolicy: "No returns allowed",
    reviews: [
      {
        comment: "Absolutely love this piece!",
        date: "2023-06-01T00:00:00Z",
        rating: 5,
        revierEmail: "reviewer3@example.com",
        revierName: "Reviewer Three",
      },
    ],
    shippingInformation: "Heavy item, additional shipping fees apply",
    sku: "SKU54321",
    stock: 0,
    tags: ["furniture", "living room", "luxury"],
    thumbnail: "https://example.com/product3-thumbnail.jpg",
    title: "Product C",
    warrantyInformation: "5-year extended warranty",
    weight: 30,
  },
];
