import { Product } from "@/types/home/home";

export const mockProducts: Array<Product> = [
    { id: 1, title: "Product 1", price: 20, images: [], availabilityStatus: "In Stock", brand: "Brand A", category: "Category A", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 2, title: "Product 2", price: 50, images: [], availabilityStatus: "In Stock", brand: "Brand B", category: "Category A", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 3, title: "Product 3", price: 80, images: [], availabilityStatus: "In Stock", brand: "Brand C", category: "Category B", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 4, title: "Product 4", price: 100, images: [], availabilityStatus: "In Stock", brand: "Brand D", category: "Category B", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 5, title: "Product 5", price: 150, images: [], availabilityStatus: "In Stock", brand: "Brand E", category: "Category C", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 6, title: "Product 6", price: 200, images: [], availabilityStatus: "In Stock", brand: "Brand F", category: "Category C", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 7, title: "Product 7", price: 250, images: [], availabilityStatus: "In Stock", brand: "Brand G", category: "Category C", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 8, title: "Product 8", price: 300, images: [], availabilityStatus: "In Stock", brand: "Brand H", category: "Category D", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 9, title: "Product 9", price: 350, images: [], availabilityStatus: "In Stock", brand: "Brand I", category: "Category D", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
    { id: 10, title: "Product 10", price: 400, images: [], availabilityStatus: "In Stock", brand: "Brand J", category: "Category D", description: "", dimensions: { width: 10, height: 10, depth: 10 }, discountPercentage: 5, meta: { createdAt: "", updatedAt: "" }, minimumOrderQuantity: 1, rating: 4, returnPolicy: "", reviews: [], shippingInformation: "", sku: "", stock: 10, tags: [], thumbnail: "", warrantyInformation: "", weight: 1 },
  ];